server:
  port: 8080

#Pass API key as environment variable, e.g. -DNEO4J_URI=your-uri, -DNEO4J_PASSWORD=your-password
spring:
  mustache:
    check-template-location: false
  devtools:
    restart:
      additional-exclude: dev/hilla/openapi.json
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD}

#Pass API key as environment variable, e.g. -DTOGETHER_AI_API_KEY=your-api-key
ai:
  api-key: ${TOGETHER_AI_API_KEY}
  base-url: https://api.together.xyz/v1
  chat-model-name: meta-llama/Meta-Llama-3.1-405B-Instruct-Lite-Pro-lora
#  chat-model-name: meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application

#Logging levels
logging:
  level:
    root: INFO
    org.springframework.boot: INFO
    org.springframework.data.neo4j: INFO
    org.neo4j.driver: INFO
    org.springframework.beans.factory.support: INFO
    org.springframework.data.convert: INFO
    org.springframework.context: INFO
    com.neo4j.ai: INFO